### ISSUE TITLE
反馈2个小问题

### ISSUE THREAD

**Issue by chzzfly** [jzj1993/PublishMarkdown#3]
1.  文章字数在8000左右，编辑器就无法执行“保存”功能了。
2.  “发布模式” 设置为【自动判断】，打开一篇新文章后，又默认为【手动确认】。

最后感谢作者发布如此好用的小工具，加油(｀・ω・´)

**Comment by xiaomingio** [comment]
好的，感谢反馈。第二个问题我自己也觉得可以完善一下，第一个不能保存的问题我之前遇到过，但是一直没有定位到原因……我最近抽空完善一下~
