### ISSUE TITLE
反馈一个问题和一个建议

### ISSUE THREAD

**Issue by chzzfly** [jzj1993/PublishMarkdown#4]
- 问题1.如图，不能判断已存在的文章，在原有的url-2，这难道是手动加了特色图片的原因吗？
![image](https://user-images.githubusercontent.com/48624829/79123986-f1fed980-7dcd-11ea-9592-3d40c287e5a9.png)
![image](https://user-images.githubusercontent.com/48624829/79124094-2c687680-7dce-11ea-9c20-3ea549979fd8.png)

- 建议1.示例文章的 category 应该改成 categories 这个词更通用，我发现在本软件里两者都是可以的，但如果搭建静态博客的话，很多都是 categories 而非 category，这可能会给小白带来困扰，比如我-_-||

![image](https://user-images.githubusercontent.com/48624829/79124364-c03a4280-7dce-11ea-8d18-013759aa3432.png)

**Comment by xiaomingio** [comment]
1、判断已存在文章的原理是，旧文章也是用本工具发布的，会在本地保存旧文章的url和发布后的id对应关系，重新发布相同url的文章时会用本地保存的id编辑旧文章。和插入特色图片没什么关系，自己编辑WordPress已有文章，不会改变文章的id。

但是如果旧文章不是本工具发布的，或者本地缓存被清除了，是没办法判断已经存在的文章的。实现上的具体原因是，MetaWeblog接口并没有提供使用url查找已有文章的方法，这个目前无解。

如果已经有一篇通过其他方式发布好的旧文章，想直接编辑这篇文章，目前还没有提供这个功能（属于需要依赖技术细节的问题，也在考虑在操作上应该怎么设计比较好理解，如果有好的建议也可以提）。一个临时的Hack做法是你可以手工编辑配置文件，自己把url和旧文章的id加进去（旧文章的id可以从WordPress后台找到）。Mac系统中的文件位置是：`~/Library/Application Support/Publish Markdown/cache-post-xxx.json`，其他系统还得搜一下`Publish Markdown`。

2、问题2我觉得问题不大，按照你习惯的方式使用，预览的时候是正确的就没问题了。严格来说，个人认为一篇文章目录应该只有一个，而标签可以有多个，category用单数，tags用复数。考虑到不同人的习惯可能不同，所以索性都给兼容了……

**Comment by chzzfly** [comment]
第一个问题的原因应该就是在两个电脑上分别使用这个工具了。
第二个问题主要是和其他静态博客，比如 hugo hexo 兼容的问题，这个如果懂的话就不存在什么问题了。
感谢你详细的回复，我正在学习编程方面的知识，恨不能和你一起开发这个软件呀……

**Comment by xiaomingio** [comment]
欢迎提PR~ 主要就是前端的知识，会一点Vue和Node.js就可以了~

**Comment by xiaoyaoyuxin** [comment]
感谢开发的这款好工具。

希望能提供一下多台电脑同步的功能，可以配合onedirve之类的。

**Comment by xiaomingio** [comment]
> 感谢开发的这款好工具。
> 
> 希望能提供一下多台电脑同步的功能，可以配合onedirve之类的。

多台电脑同步直接用onedrive、百度网盘、git之类工具就行了，这个只是简单的发布到WordPress，和文件同步没有关系。
